### ISSUE TITLE
invalid TLE results in "Check your internet connection"

### ISSUE THREAD

**Issue by DC7IA** [rt-bishop/Look4Sat#23] opened 2020-08-30 09:43 UTC
I've tried using [1], but this results in "Check your internet connection".

I then thought this might be because Look4Sat does not know what to do with the header.

So next I tried [2], which worked.

[1] https://www.amsat.org/tle/current/nasa.all
[2] https://www.amsat.org/tle/current/nasabare.txt

**Comment by rt-bishop** [comment] 2020-08-30 14:31
Yeah, I've just checked, the same behaviour is on my devices. It's the header that stops it from updating. TLE update via text files is super sensitive to the content and AFAIK, Celestrak is switching to JSON-type TLE as they are a lot more flexible. So in the future I'll add a proper handling of both. For now I'll just add the nasabare source on top of celestrak source.

**Comment by rt-bishop** [comment] 2020-09-10 10:59
The issue is fixed in recent 0d3c9887e8c20bf29ef7719724b35f20b9a4dcda. The AMSAT TLE source is added by default and overwrites the Celestrak data correctly.

**Closed by rt-bishop** 2020-09-10 10:59 UTC
