### ISSUE TITLE
List of passes does not refresh automatically when app is opened

### ISSUE THREAD

**Issue by therman89** [rt-bishop/Look4Sat#12] opened 2020-03-29 17:32 UTC
I need to manually refresh the list after I open the app. I think this should be automatic.

**Comment by rt-bishop** [comment] 2020-03-30 20:20
The issue is fixed in e52e6ec commit. Will be shipped in v1.3.4 by the end of the week.

**Comment by therman89** [comment] 2020-04-24 05:42
I need to reopen this, as the function is buggy. If you use the app, close it, then open it later, the list dies not refresh, instead it shows wrong predictions.
This bug might be connected with the other, that every time you refresh the list of passes, the AOS and LOS times can change by 1-2s every time.

See:
https://photos.app.goo.gl/kBenDUsFYKzPQD4Z8

**Comment by rt-bishop** [comment] 2020-05-27 15:01
> I need to reopen this, as the function is buggy. If you use the app, close it, then open it later, the list dies not refresh, instead it shows wrong predictions.
> This bug might be connected with the other, that every time you refresh the list of passes, the AOS and LOS times can change by 1-2s every time.
> 
> See:
> https://photos.app.goo.gl/kBenDUsFYKzPQD4Z8

As far as I know the time change by 1-2s is an issue of predict4java lib, but I will look into that issue.

**Comment by rt-bishop** [comment] 2020-09-10 10:46
Fixed in bfefae8

**Closed by rt-bishop** 2020-09-10 10:46 UTC
